exclude:
  - external_repos/**
source: sample_web
# Setup
title:        Audio Demo
tagline:      Adversarial Attack on 0-shot TTS
paginate:     1
locale:       "en"
url: "https://yrymax.github.io"
baseurl: "/AdvSpeech"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
