name: advspeech
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - ipython
  - librosa
  - matplotlib
  - numpy<2
  - pandas
  - pesq
  - pyworld
  - pyyaml
  - tqdm
  - torchmetrics
  - pip:
      - praat-parselmouth
      - resemblyzer
      - git+https://github.com/wenet-e2e/wespeaker.git
