# Setup
title:        Audio Demo
tagline:      Adversarial Attack on 0-shot TTS
baseurl:      "/AdvSpeech/sample_web"
url:          "https://yryMax.github.io"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Renyi Yang
  url:        https://github.com/yryMax

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown